# Generated by Django 5.1 on 2024-12-06 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='location.location'),
        ),
    ]
